apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${{values.name}}-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: ${{values.name}}-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: ${{values.owner | replace("group:", "") | replace("team-", "")}}/${{values.name}}
