{%- if values.database == "aurora-postgresql" %}
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>

development:
  <<: *default
  database: ${{values.name}}_development

test:
  <<: *default
  database: ${{values.name}}_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "${{values.name}}_production") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 10) %>
{%- endif %}

{%- if values.database == "aurora-mysql" %}
default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 3306) %>
  username: <%= ENV.fetch("DATABASE_USER", "root") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>

development:
  <<: *default
  database: ${{values.name}}_development

test:
  <<: *default
  database: ${{values.name}}_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "${{values.name}}_production") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 10) %>
{%- endif %}

{%- if values.database == "none" %}
# No database configured
{%- endif %}
